/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Paynow Developer Hub",
  "tagline": "Integrate With Paynow & #GetPaid",
  "url": "https://paynowdocs.devpreview.net",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "/img/favicon.png",
  "projectName": "paynow-docs",
  "organizationName": "PaynowZW",
  "scripts": [
    "/js/custom.js"
  ],
  "themeConfig": {
    "algolia": {
      "appId": "3H7ITVC7MS",
      "apiKey": "1a1e673b71df14e33281d0447c1d63f7",
      "indexName": "paynow",
      "algoliaOptions": {},
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "navbar": {
      "title": "Paynow Developer Hub",
      "logo": {
        "alt": "Paynow Logo",
        "src": "img/paynow.logo.png"
      },
      "items": [
        {
          "to": "docs/quickstart",
          "label": "Documentation",
          "position": "left"
        },
        {
          "to": "about",
          "label": "About",
          "position": "left"
        },
        {
          "to": "help",
          "label": "Help",
          "position": "left"
        },
        {
          "href": "https://forums.paynow.co.zw/",
          "label": "Forums",
          "position": "right"
        },
        {
          "href": "https://forums.paynow.co.zw/signup",
          "label": "Sign Up / Sign In",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "docs/quickstart"
            },
            {
              "label": "API Reference",
              "to": "docs/paynow_api"
            },
            {
              "label": "Frequently Asked Questions",
              "to": "docs/#"
            },
            {
              "label": "Artwork & Buttons",
              "to": "docs/artwork"
            }
          ]
        },
        {
          "title": "Libraries & Plugins",
          "items": [
            {
              "label": "PHP",
              "to": "docs/php_quickstart"
            },
            {
              "label": ".NET",
              "to": "docs/csharp_quickstart"
            },
            {
              "label": "Node.JS",
              "to": "docs/nodejs_quickstart"
            },
            {
              "label": "Python",
              "to": "docs/python_quickstart"
            },
            {
              "label": "Java",
              "to": "docs/java_quickstart"
            }
          ]
        },
        {
          "title": "Plugins",
          "items": [
            {
              "label": "WooCommerce",
              "to": "docs/woocommerce"
            },
            {
              "label": "Gravity Forms",
              "to": "docs/gravity_forms"
            },
            {
              "label": "Easy Digital Downloads",
              "to": "docs/easy_digital_downloads"
            },
            {
              "label": "Shopify",
              "to": "docs/shopify"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discussion Forums",
              "href": "https://forums.paynow.co.zw/"
            },
            {
              "label": "Blogs & Tutorials",
              "to": "blog"
            },
            {
              "label": "Github",
              "href": "https://github.com/paynow"
            },
            {
              "label": "Facebook",
              "href": "https://facebook.com/paynowzw"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/paynowzw"
            }
          ]
        }
      ],
      "logo": {
        "alt": "Paynow Zimbabwe",
        "src": "img/paynow.png",
        "href": "https://www.paynow.co.zw/"
      },
      "copyright": "Copyright © 2024 Paynow Zimbabwe"
    },
    "image": "img/Paynow-Dev-Hub-Sharer-Image.png",
    "colors": {
      "primary": "#175ff8",
      "secondary": "#ffffff"
    },
    "twitterImage": "img/paynow.logo.png",
    "disableHeaderTitle": true,
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "prism": {
      "additionalLanguages": [
        "php",
        "powershell",
        "csharp",
        "rest"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "C:\\xampp\\htdocs\\docs\\website\\sidebars.js"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "gtag": {
          "trackingID": "UA-126207230-1",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
